### ISSUE TITLE
Task: Create The Rollup File

### ISSUE THREAD

**Issue by massimovignelli** [kaentor/kaentor#2]
#### Key

> Id: **KAEN-2**
Project: [**Product**](https://github.com/kaentor/kaentor/projects/1)

#### Description

Create the `rollup` configuration file.

#### Task Checklist

- [ ] Create the file.
- [ ] Install `rollup` in the project and add basic configuration.
  - [ ] Enable _ESModules_, _Common JS_ and _UMD_ formats.
- [ ] Use `Mocha` and `Chai` as a _Test Suite_.
- [ ] Create a _development_ and _production_ configuration.
- [ ] Enable commands through CLI to run both scripts.

#### Assignees

- [X] Finall assign @kyoeuler
