### ISSUE TITLE
Task: Create the design proposal for Kæntor

### ISSUE THREAD

**Issue by massimovignelli** [kaentor/kaentor#3]
#### Key

> Id: **KAEN-3**
Project: **[Product](https://github.com/kaentor/kaentor/projects/1)**

#### Description

For Kæntor, I need a proposal to establish all the features that will contain the project.

#### Task Checklist

- [ ] Create a README.md file.
- [ ] List all the possible features.
- [ ] Write the needed additional notes.

#### Assignees

- [x] Final assign @kyoeuler

**Comment by massimovignelli** [comment]
I’ll start the development of this feature.

###### History Log is at: [Issue KAEN-3](https://kyoeuler.atlassian.net/browse/KAEN-3?atlOrigin=eyJpIjoiMWUxNGE5MDZkZjU2NDBkODllMGEyMjc5ZjA2ZTdlZjQiLCJwIjoiaiJ9)
